const express = require('express');
const router = express.Router();

const authRoutes = require('./modules/Auth/Users/users.routes');
const companyRoutes = require('./modules/Masters/CompanyMasters/company.routes');
const countryRoutes = require('./modules/Masters/CountryMasters/country.routes');
const stateRoutes = require('./modules/Masters/StateMasters/state.routes');
const cityRoutes = require('./modules/Masters/CityMasters/city.routes');
const currencyRoutes = require('./modules/Masters/CurrencyMasters/currency.routes');
const portRoutes = require('./modules/Masters/PortMasters/port.routes');
const shippingLineRoutes = require('./modules/Masters/ShippingLineMasters/shippingLine.routes');
const containerTypeRoutes = require('./modules/Masters/ContainerTypeMasters/containerType.routes');
const transportModeRoutes = require('./modules/Masters/TransportModeMasters/transportMode.routes');
const commodityRoutes = require('./modules/Masters/CommodityMasters/commodity.routes');
const customerRoutes = require('./modules/Masters/CustomerMasters/customer.routes');
const vendorRoutes = require('./modules/Masters/VendorMasters/vendor.routes');
const warehouseRoutes = require('./modules/Masters/WarehouseMasters/warehouse.routes');
const vehicleRoutes = require('./modules/Masters/VehicleMasters/vehicle.routes');
const driverRoutes = require('./modules/Masters/DriverMasters/driver.routes');
const departmentRoutes = require('./modules/Masters/DepartmentMasters/department.routes');
const designationRoutes = require('./modules/Masters/DesignationMasters/designation.routes');
const employeeRoutes = require('./modules/Masters/EmployeeMasters/employee.routes');
const uomRoutes = require('./modules/Masters/UOMMasters/uom.routes');
const packageTypeRoutes = require('./modules/Masters/PackageTypeMasters/packageType.routes');
const incotermRoutes = require('./modules/Masters/IncotermMasters/incoterm.routes');
const chargeRoutes = require('./modules/Masters/ChargeMasters/charge.routes');
const paymentTermRoutes = require('./modules/Masters/PaymentTermMasters/paymentTerm.routes');

// Mount routes
router.use('/auth', authRoutes);
router.use('/company', companyRoutes);
router.use('/country', countryRoutes);
router.use('/state', stateRoutes);
router.use('/city', cityRoutes);
router.use('/currency', currencyRoutes);
router.use('/port', portRoutes);
router.use('/shipping-line', shippingLineRoutes);
router.use('/container-type', containerTypeRoutes);
router.use('/transport-mode', transportModeRoutes);
router.use('/commodity', commodityRoutes);
router.use('/customer', customerRoutes);
router.use('/vendor', vendorRoutes);
router.use('/warehouse', warehouseRoutes);
router.use('/vehicle', vehicleRoutes);
router.use('/driver', driverRoutes);
router.use('/department', departmentRoutes);
router.use('/designation', designationRoutes);
router.use('/employee', employeeRoutes);
router.use('/uom', uomRoutes);
router.use('/package-type', packageTypeRoutes);
router.use('/incoterm', incotermRoutes);
router.use('/charge', chargeRoutes);
router.use('/payment-term', paymentTermRoutes);

module.exports = router;
