const express = require('express');
const router = express.Router();

const authRoutes = require('./modules/Auth/Users/users.routes');
const companyRoutes = require('./modules/Masters/Foundation/CompanyMasters/company.routes');
const countryRoutes = require('./modules/Masters/Foundation/CountryMasters/country.routes');
const stateRoutes = require('./modules/Masters/Foundation/StateMasters/state.routes');
const cityRoutes = require('./modules/Masters/Foundation/CityMasters/city.routes');
const currencyRoutes = require('./modules/Masters/Foundation/CurrencyMasters/currency.routes');
const portRoutes = require('./modules/Masters/Logistics/PortMasters/port.routes');
const shippingLineRoutes = require('./modules/Masters/Logistics/ShippingLineMasters/shippingLine.routes');
const containerTypeRoutes = require('./modules/Masters/Common/ContainerTypeMasters/containerType.routes');
const transportModeRoutes = require('./modules/Masters/Common/TransportModeMasters/transportMode.routes');
const commodityRoutes = require('./modules/Masters/Common/CommodityMasters/commodity.routes');
const customerRoutes = require('./modules/Masters/Business/CustomerMasters/customer.routes');
const vendorRoutes = require('./modules/Masters/Business/VendorMasters/vendor.routes');
const warehouseRoutes = require('./modules/Masters/Logistics/WarehouseMasters/warehouse.routes');
const vehicleRoutes = require('./modules/Masters/Logistics/VehicleMasters/vehicle.routes');
const driverRoutes = require('./modules/Masters/Logistics/DriverMasters/driver.routes');
const departmentRoutes = require('./modules/Masters/Organization/DepartmentMasters/department.routes');
const designationRoutes = require('./modules/Masters/Organization/DesignationMasters/designation.routes');
const employeeRoutes = require('./modules/Masters/Organization/EmployeeMasters/employee.routes');
const uomRoutes = require('./modules/Masters/Common/UOMMasters/uom.routes');
const packageTypeRoutes = require('./modules/Masters/Common/PackageTypeMasters/packageType.routes');
const incotermRoutes = require('./modules/Masters/Common/IncotermMasters/incoterm.routes');
const chargeRoutes = require('./modules/Masters/Common/ChargeMasters/charge.routes');
const paymentTermRoutes = require('./modules/Masters/Foundation/PaymentTermMasters/paymentTerm.routes');
const bulkImportRoutes = require('./modules/Masters/bulkImport.routes');
const shipmentRoutes = require('./modules/Operations/Shipment/shipment.routes');
const jobRoutes = require('./modules/Operations/Job/job.routes');

// Mount routes
router.use('/auth', authRoutes);
router.use('/company', companyRoutes);
router.use('/country', countryRoutes);
router.use('/state', stateRoutes);
router.use('/city', cityRoutes);
router.use('/currency', currencyRoutes);
router.use('/port', portRoutes);
router.use('/shipping-line', shippingLineRoutes);
router.use('/container-type', containerTypeRoutes);
router.use('/transport-mode', transportModeRoutes);
router.use('/commodity', commodityRoutes);
router.use('/customer', customerRoutes);
router.use('/vendor', vendorRoutes);
router.use('/warehouse', warehouseRoutes);
router.use('/vehicle', vehicleRoutes);
router.use('/driver', driverRoutes);
router.use('/department', departmentRoutes);
router.use('/designation', designationRoutes);
router.use('/employee', employeeRoutes);
router.use('/uom', uomRoutes);
router.use('/package-type', packageTypeRoutes);
router.use('/incoterm', incotermRoutes);
router.use('/charge', chargeRoutes);
router.use('/payment-term', paymentTermRoutes);
router.use('/masters/bulk-import', bulkImportRoutes);
router.use('/shipment', shipmentRoutes);
router.use('/job', jobRoutes);

module.exports = router;
